"""
DOCX Generator Module
Creates Word documents from extracted text
"""

from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
import io
from datetime import datetime


class DocxGenerator:
    """Generate Word documents from text"""
    
    def __init__(self):
        """Initialize the document generator"""
        self.document = None
    
    def create_document(self, text, title="OCR Extracted Text", add_metadata=True):
        """
        Create a new Word document with the extracted text
        
        Args:
            text: The text to add to document
            title: Document title (default: "OCR Extracted Text")
            add_metadata: Whether to add metadata header (default: True)
            
        Returns:
            Document object
        """
        # Create new document
        self.document = Document()
        
        # Add title
        title_paragraph = self.document.add_heading(title, level=0)
        title_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Add metadata if requested
        if add_metadata:
            self._add_metadata()
        
        # Add separator
        self.document.add_paragraph('_' * 80)
        
        # Add the extracted text
        if text.strip():
            # Split text into paragraphs and add each
            paragraphs = text.split('\n')
            for para_text in paragraphs:
                if para_text.strip():  # Only add non-empty paragraphs
                    p = self.document.add_paragraph(para_text)
                    # Set font
                    for run in p.runs:
                        run.font.size = Pt(11)
                        run.font.name = 'Calibri'
                else:
                    # Add empty paragraph for spacing
                    self.document.add_paragraph()
        else:
            # No text found
            p = self.document.add_paragraph("No text was detected in the image.")
            p.italic = True
        
        return self.document
    
    def _add_metadata(self):
        """Add metadata section to document"""
        # Add metadata
        meta = self.document.add_paragraph()
        meta.add_run('Generated by: ').bold = True
        meta.add_run('OCR Image-to-Word App\n')
        
        meta.add_run('Date: ').bold = True
        meta.add_run(f'{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n')
        
        meta.add_run('Source: ').bold = True
        meta.add_run('Image OCR Processing')
        
        # Set smaller font for metadata
        for run in meta.runs:
            run.font.size = Pt(9)
            run.font.name = 'Calibri'
    
    def create_document_with_sections(self, text, title="OCR Extracted Text", 
                                     confidence_score=None):
        """
        Create document with formatted sections
        
        Args:
            text: Extracted text
            title: Document title
            confidence_score: OCR confidence score (0-1)
            
        Returns:
            Document object
        """
        self.document = Document()
        
        # Add title
        title_para = self.document.add_heading(title, level=0)
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Add metadata with confidence score
        meta = self.document.add_paragraph()
        meta.add_run('Generated: ').bold = True
        meta.add_run(f'{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n')
        
        if confidence_score is not None:
            meta.add_run('OCR Confidence: ').bold = True
            meta.add_run(f'{confidence_score*100:.1f}%\n')
        
        for run in meta.runs:
            run.font.size = Pt(9)
        
        # Separator
        self.document.add_paragraph('_' * 80)
        
        # Add main content
        self.document.add_heading('Extracted Text:', level=1)
        
        if text.strip():
            paragraphs = text.split('\n')
            for para_text in paragraphs:
                if para_text.strip():
                    p = self.document.add_paragraph(para_text)
                    for run in p.runs:
                        run.font.size = Pt(11)
                        run.font.name = 'Calibri'
                else:
                    self.document.add_paragraph()
        else:
            p = self.document.add_paragraph("No text detected in the image.")
            p.italic = True
        
        return self.document
    
    def save_to_bytes(self):
        """
        Save document to bytes (for download in Streamlit)
        
        Returns:
            BytesIO object containing the document
        """
        if self.document is None:
            raise ValueError("No document created. Call create_document() first.")
        
        # Save to BytesIO
        file_stream = io.BytesIO()
        self.document.save(file_stream)
        file_stream.seek(0)
        return file_stream
    
    def save_to_file(self, filename):
        """
        Save document to file
        
        Args:
            filename: Path to save the document
        """
        if self.document is None:
            raise ValueError("No document created. Call create_document() first.")
        
        self.document.save(filename)
    
    @staticmethod
    def create_simple_document(text, filename=None):
        """
        Quick method to create a simple document
        
        Args:
            text: Text to add
            filename: Optional filename to save (if None, returns BytesIO)
            
        Returns:
            BytesIO if filename is None, else None (saves to file)
        """
    def create_formatted_document(self, structured_data, title="OCR Extracted Text", confidence_score=None):
        """
        Create document with formatting preserved from structured data
        
        Args:
            structured_data: List of dicts with text and layout info
            title: Document title
            confidence_score: Overall confidence score
            
        Returns:
            Document object
        """
        self.document = Document()
        
        # Add title
        title_para = self.document.add_heading(title, level=0)
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Add metadata
        meta = self.document.add_paragraph()
        meta.add_run('Generated: ').bold = True
        meta.add_run(f'{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n')
        
        if confidence_score is not None:
            meta.add_run('OCR Confidence: ').bold = True
            meta.add_run(f'{confidence_score*100:.1f}%\n')
        
        for run in meta.runs:
            run.font.size = Pt(9)
        
        self.document.add_paragraph('_' * 80)
        
        # Process structured data
        if not structured_data:
            p = self.document.add_paragraph("No text detected in the image.")
            p.italic = True
            return self.document
            
        current_block = -1
        current_para = -1
        p = None
        
        # If simple text list (fallback)
        if isinstance(structured_data[0], dict) and 'block' not in structured_data[0]:
             self.document.add_paragraph(structured_data[0]['text'])
             return self.document

        # Provide a buffer for line construction
        line_buffer = []
        last_line_num = -1
        
        # Group by blocks and paragraphs
        for item in structured_data:
            block_num = item['block']
            para_num = item['para']
            line_num = item['line']
            text = item['text']
            
            if block_num != current_block or para_num != current_para:
                # Flush previous line if any
                if line_buffer:
                    if p is None:
                         p = self.document.add_paragraph()
                    
                    # Add space before appending new text if not start of paragraph
                    if len(p.runs) > 0:
                        p.add_run(' ')
                        
                    run = p.add_run(' '.join(line_buffer))
                    run.font.size = Pt(11)
                    run.font.name = 'Calibri'
                    line_buffer = []

                # New paragraph
                p = self.document.add_paragraph()
                current_block = block_num
                current_para = para_num
                last_line_num = line_num
                
            elif line_num != last_line_num:
                # New line in same paragraph -> add to buffer
                if line_buffer:
                     run = p.add_run(' '.join(line_buffer) + ' ')
                     run.font.size = Pt(11)
                     run.font.name = 'Calibri'
                     line_buffer = []
                last_line_num = line_num
            
            line_buffer.append(text)
            
        # Flush remaining buffer
        if line_buffer and p is not None:
            run = p.add_run(' '.join(line_buffer))
            run.font.size = Pt(11)
            run.font.name = 'Calibri'
            
        return self.document

